#!/usr/bin/env bash

set -e

function execute {
    cmd=("$@")
	echo
    echo "Executing ${cmd[*]} ..."
	echo
    # execute the command:
    "${cmd[@]}"
}

function confirm() {
    read -p "$1 ([y]es or [N]o): "
    case $(echo $REPLY | tr '[A-Z]' '[a-z]') in
        y|yes) echo "yes" ;;
        *)     echo "no" ;;
    esac
}

function getMessage() {
	if [[ -z "$@" ]]
	then
		echo false;
	fi
	
	echo $@
}

function showHelp() {
cat <<'TXT'
versiontag
==========

Automates version tag creation.

Commands:   patch|minor|major|current 'Tag message'
            remove
            current

Examples:
---------

Show current version: ./versiontag current
Patch version:        ./versiontag patch 'Fix broken view'
Minor version:        ./versiontag minor 'Add Customer filter by email'
Major version:        ./versiontag major 'Blog module'
Remove last version:  ./versiontag remove

TXT
	exit 0
}

function showSuccess() {
	echo
	echo "Tag v$major.$minor.$patch was created in local repository."
	echo
	echo "Push it:"
	echo
	echo "    git push origin v$major.$minor.$patch"
	echo
	echo "Delete tag:"
	echo
	echo "    git tag -d v$major.$minor.$patch"
	echo
}

function updateSemverFile() {
	exec 3<> .semver

	echo "---" >&3
	echo ":major: $major" >&3
	echo ":minor: $minor" >&3
	echo ":patch: $patch" >&3
	echo >&3
	echo ":notes: $msg" >&3
	exec 3>&-
	
	execute git add .semver
	execute git commit -m "Update .semver file"
	execute git push
}


lasttag=`git describe --tags --long 2> /dev/null` || true

if [[ -z "$lasttag" ]]; then
	lasttag='v0.0.0'
fi

cleantag=${lasttag%%-*}

parts=(${cleantag//./ })

major=${parts[0]:1}
minor=${parts[1]}
patch=${parts[2]}

major=${major:0}
minor=${minor:0}
patch=${patch:0}

last="v$major.$minor.$patch"

mode=''
force=false
for ((i = 1; i <= $#; i++ )); do
	case ${!i} in
		"-f"|"--force")
			force=true
			;;
		"-h"|"--help")
			showHelp
			;;
		"patch")
			patch=$((patch + 1))
			let i++
			msg=$(getMessage "${!i}")
			mode='patch'
			;;
		"minor")
			minor=$((minor + 1))
			patch=0
			let i++
			msg=$(getMessage "${!i}")
			mode='minor'
			;;
		"major")
			major=$((major + 1))
			minor=0
			patch=0
			let i++
			msg=$(getMessage "${!i}")
			mode='major'
			;;
		"current")
			echo "Current version: $last"
			exit 0
			;;
		"remove")
			if [[ "yes" == $(confirm "Do you want to remove $last?") ]]; then
				execute git tag -d "$last"
				execute git push origin ":$last"
				updateSemverFilegi
			fi
			exit 0
			;;
		"help")
			showHelp
			;;
		*)
			echo "${!i} option is not valid"
			exit 1
			;;
	esac
done

if [[ false == "$msg" ]]; then
	echo
	echo "No message."
	exit 1;
fi

if [[ -z "$mode" ]]; then
    echo "No mode selected"
	showHelp;
	exit 0
fi

echo "Current version : $last"
echo "New tag         : v$major.$minor.$patch"
echo
echo "Message         : $msg"

if [[ "$force" = true ]]; then
	execute git tag -a "v$major.$minor.$patch" -m "$msg ($mode version)"
	execute git push origin "v$major.$minor.$patch"
	updateSemverFile
	echo 
	echo "Version tag created and pushed"
	exit 0;
fi

if [[ "no" == $(confirm "Do you agree?") ]]; then
	echo
	echo "No tag was created"
	exit 0;
fi

execute git tag -a "v$major.$minor.$patch" -m "$msg ($mode version)"
	
showSuccess;
	
if [[ "yes" == $(confirm "Do you want to push this tag right now?") ]]; then
	execute git push origin "v$major.$minor.$patch"
fi

updateSemverFile

exit 0